* Making use of the configuration file * Removed popup notifications as they do not make any sense to have in the first place * Code simplification

diff --git a/imgurbash2 b/imgurbash2
--- a/imgurbash2
+++ b/imgurbash2
@@ -26,8 +26,6 @@
 # REQUIRED: curl
 # OPTIONAL:
 #    * xsel or xclip for copying URLs to your clipboard (Linux)
-#    * notify-send for notifications (Linux)
-#    * growlnotify or terminal-notifier for notifications (macOS)
 #--------------------------------------------------------------------
 #
 # The URLs will be output on your terminal. If you have xsel or xclip they
@@ -36,10 +34,11 @@
 set -a
 
 readonly SELF=${0##*/}
-readonly CONF_ROOT="$HOME/.config/imgurbash2"
-
-readonly CONF_FILE="$CONF_ROOT/config"
 readonly VERSION="3.0"
+readonly CONF_ROOT="$HOME/.config/imgurbash2"
+readonly CONF_FILE="$CONF_ROOT/config"
+readonly CREDENTIALS_FILE="$CONF_ROOT/credentials.conf"
+readonly ANON_CLIENT_ID=4f0d009df8e7de6  # client_id to use for non-authenticated operations
 readonly TOKEN_URL="https://api.imgur.com/oauth2/token"
 readonly JOB_ID="$$"
 uname | grep -q Darwin && IS_MAC=1 || IS_MAC=0
@@ -189,51 +188,6 @@ upload_image() {
 }
 
 
-# Pops a notification message
-#
-# @param {string}  -t ttl  OPTIONAL message ttl in millisec (linux only atm);
-#                          value of 0 means no ttl;
-# @param {string}  lvl     message level. ERROR | INFO
-# @param {string}  msg     message to print.
-#
-# @returns {void}
-notify() {
-	local opt ttl lvl msg default_ttl OPTIND
-
-	default_ttl=5000
-
-	while getopts "t:" opt; do
-		case "$opt" in
-			t) ttl="$OPTARG" ;;
-			*) usage; exit 1 ;;  # do not call fail() to avoid circular dep
-		esac
-	done
-	shift $((OPTIND-1))
-
-
-	lvl="$1"
-	msg="$2"
-
-	ttl="${ttl:-$default_ttl}"
-
-	[[ "$ENABLE_NOTIFICATIONS" != true ]] && return
-
-	if [[ "$IS_MAC" -eq 1 ]]; then
-		if which growlnotify &>/dev/null; then
-			growlnotify --title "$SELF" --message "$msg"
-		elif which terminal-notifier &>/dev/null; then
-			terminal-notifier -title "$SELF" -message "$msg"
-		fi
-	elif command -v notify-send &>/dev/null; then
-		if [[ "$lvl" == ERROR ]]; then
-			notify-send -u critical -c "im.error" -t "$ttl" "$SELF" "$msg"
-		elif [[ "$NOTIFY_LEVEL" != ERROR ]]; then
-			notify-send -u low -c "transfer.complete" -t "$ttl" "$SELF" "$msg"
-		fi
-	fi
-}
-
-
 # Parses string field value from given json input.
 #
 # E.g.  '"error":"Invalid client_id"' ==> string = "error", value = "Invalid client_id"
@@ -287,9 +241,9 @@ copy_to_clipboard() {
 	elif [[ -n "$DISPLAY" ]]; then
 		{ command -v xsel &>/dev/null && echo -n "$input" | xsel --input --clipboard; } \
 			|| { command -v xclip &>/dev/null && echo -n "$input" | xclip -selection clipboard; } \
-			|| err -L "didn't copy to clipboard - xsel nor xclip are installed"
+			|| err -L "Didn't copy to clipboard:  xsel nor xclip are installed"
 	else
-		err -L "Haven't copied to the clipboard:  no \$DISPLAY"
+		err -L "Didn't copy to the clipboard:  no \$DISPLAY"
 	fi
 }
 
@@ -306,19 +260,19 @@ upload_images() {
 
 	for file in "${files[@]}"; do
 		response="$(upload_image "$file")"
-		is_request_success "$response" || { err "uploading [$file] failed"; HAS_ERRORS=1; continue; }
+		is_request_success "$response" || { err "Uploading [$file] failed"; HAS_ERRORS=1; continue; }
 
 		# get image url link
 		url="$(parse_str_field "$response" link | sed -e 's/\\//g')"
-		is_valid_url "$url" || err "uploaded image resulted in [$url] link"
+		is_valid_url "$url" || err "Uploaded image resulted in [$url] link"
 		dhash="$(parse_str_field "$response" deletehash)"
-		[[ -z "$dhash" ]] && err "no deletehash found in image [$file] upload response [$response]"
+		[[ -z "$dhash" ]] && err "No deletehash found in image [$file] upload response [$response]"
 
 		if [[ -n "$AUTO_DELETE_DELAY" ]]; then
-			echo "$url (Deleting image in $AUTO_DELETE_DELAY)"
+			info "$url (Deleting image in $AUTO_DELETE_DELAY)"
 			nohup /usr/bin/env bash -c "sleep $AUTO_DELETE_DELAY_SEC && delete_image_auto '$dhash' '$url'" &>/dev/null &
 		else
-			echo -e "$url (Delete Hash = $dhash)"
+			info "$url (Delete Hash = $dhash)"
 		fi
 
 		urls+=("$url")
@@ -340,9 +294,9 @@ delete_images() {
 
 	for hash in "${hashes[@]}"; do
 		response="$(api_call -r "image/${hash}" -X DELETE)"
-		is_request_success "$response" || { err "deleting hash [$hash] failed"; HAS_ERRORS=1; continue; }
+		is_request_success "$response" || { err "Deleting hash [$hash] failed"; HAS_ERRORS=1; continue; }
 
-		echo "Deletion OK:  $hash"
+		info "Deletion OK:  $hash"
 	done
 }
 
@@ -363,7 +317,7 @@ is_request_success() {
 		status="$(parse_nonstr_field "$response" status)"
 		error="$(parse_str_field "$response" error)"
 
-		err -N "request failed with status [$status]: $error"
+		err "Request failed with status [$status]: $error"
 		return 1
 	fi
 
@@ -371,19 +325,17 @@ is_request_success() {
 }
 
 
-# Prints, notifies & logs given error message.
+# Prints & logs given error message.
 #
-# @param {opt}      -N   OPTIONAL; don't open notification window.
 # @param {opt}      -L   OPTIONAL; don't log the message.
 # @param {string}   msg   error message.
 #
 # @returns {void}
 err() {
-	local opt no_notif no_log msg OPTIND
+	local opt no_log msg OPTIND
 
-	while getopts "NL" opt; do
+	while getopts "L" opt; do
 		case "$opt" in
-			N) no_notif=1 ;;
 			L) no_log=1 ;;
 			*) usage; exit 1 ;;  # do not call fail() to avoid circular dep
 		esac
@@ -392,14 +344,10 @@ err() {
 
 	msg="$1"
 
-	>&2 echo -e "${COLORS[RED]}${SELF}:${COLORS[OFF]} ${msg:-"ERR"}" 1>&2
-
-	if [[ "$no_notif" -ne 1 ]]; then
-		notify -t 0 ERROR "$msg"
-	fi
+	>&2 echo -e "ERROR: ${msg:-"ERR"}" 1>&2
 
 	if [[ "$no_log" -ne 1 ]]; then
-		echo "    ERR [$JOB_ID] $msg" >> "$LOG_FILE"
+		echo "    ERROR: [$JOB_ID] $msg" >> "$LOG_FILE"
 	fi
 }
 
@@ -411,20 +359,18 @@ fail() {
 }
 
 
-# Prints, notifies & logs given informational message.
+# Prints & logs given informational message.
 #
-# @param {opt}      -N   OPTIONAL; don't open notification window.
 # @param {opt}      -L   OPTIONAL; don't log the message.
 # @param {opt}      -S   OPTIONAL; don't print message to stderr.
 # @param {string}   msg   message.
 #
 # @returns {void}
 info() {
-	local opt no_notif no_log no_stdout msg OPTIND
+	local opt no_log no_stdout msg OPTIND
 
-	while getopts "NLS" opt; do
+	while getopts "LS" opt; do
 		case "$opt" in
-			N) no_notif=1 ;;
 			L) no_log=1 ;;
 			S) no_stdout=1 ;;
 			*) usage; fail ;;
@@ -435,11 +381,7 @@ info() {
 	msg="$1"
 
 	if [[ "$no_stdout" -ne 1 ]]; then
-		>&2 echo -e "${COLORS[YELLOW]}${SELF}:${COLORS[OFF]} ${msg:-"--info lvl message placeholder--"}"
-	fi
-
-	if [[ "$no_notif" -ne 1 ]]; then
-		notify INFO "$msg"
+		>&2 echo -e "${msg:-"--info lvl message placeholder--"}"
 	fi
 
 	if [[ "$no_log" -ne 1 ]]; then
@@ -452,10 +394,21 @@ info() {
 #
 # @returns {void}
 setup() {
+	# bash must be > 4
+	[[ "${BASH_VERSINFO[0]}" -lt 4 ]] && fail "Bash version 4 or above required, you have [${BASH_VERSINFO[0]}]"
+
+	# curl must be installed
+	command -v "curl" &>/dev/null || fail -L "'curl' is not intalled.  Please install required dependencies."
+
+	# if the imgurbash2's configuration directory does not exist then create the
+	# directory
 	[[ -d "$CONF_ROOT" ]] || mkdir -p -- "$CONF_ROOT"
-	[[ "${BASH_VERSINFO[0]}" -lt 4 ]] && fail "bash ver 4 or above required, you have [${BASH_VERSINFO[0]}]"
-	check_dependencies || fail -L "please install required dependencies"
-	[[ -n "$AUTO_DELETE_DELAY" ]] && sanitize_auto_delete_delay
+
+	# if the configuration file does not exist, then initialize it
+	if [[ ! -s "$CONF_FILE" ]]; then
+		echo "# Set to true to copy URLs of uploaded images to your clipboard" >> "$CONF_FILE"
+		echo "COPY_URL_TO_CLIP=true" >> "$CONF_FILE"
+	fi
 }
 
 
@@ -487,22 +440,6 @@ sanitize_auto_delete_delay() {
 }
 
 
-# Checks if all required dependiencies are met.
-#
-# @returns {bool}  true, if all required dependencies are installed; false if
-#                  _any_ is missing.
-check_dependencies() {
-	local prog fail
-
-	fail=0
-	for prog in curl; do
-		command -v "$prog" &>/dev/null || { err -L "[$prog] not installed"; fail=1; }
-	done
-
-	return $fail
-}
-
-
 # Loads required authentication configuration required for authenticated api calls.
 #
 # @returns {void}
@@ -518,7 +455,7 @@ load_access_token() {
 	expired="$(($(date +%s) > (TOKEN_EXPIRE_TIME - preemptive_refresh_time)))"
 
 	if [[ "$expired" -eq 1 ]]; then
-		info -LN "access token expired, refreshing..."
+		info -L "Access token expired, refreshing..."
 		refresh_access_token
 	fi
 
@@ -667,7 +604,7 @@ delete_image_auto() {
 	response="$(api_call -r "image/${dhash}" -X DELETE)"
 
 	if is_request_success "$response"; then
-		info -N "Image successfully deleted (delete hash: $dhash)."
+		info "Image successfully deleted (delete hash: $dhash)."
 	else
 		err "image @ [$url] could not be deleted (delete hash $dhash): ${response}."
 	fi
@@ -677,11 +614,12 @@ delete_image_auto() {
 #################
 ###### Entry
 #################
+
+setup
+
 ############# START CONFIG #############
 LOGIN=false  # true if we should authenticate with our own user.
 ALBUM_ID=""
-ANON_CLIENT_ID=4f0d009df8e7de6  # client_id to use for non-authenticated operations
-CREDENTIALS_FILE="$CONF_ROOT/credentials.conf"
 
 API_CALL_CONNECT_TIMEOUT_SEC=5
 API_CALL_TIMEOUT_SEC=60
@@ -690,16 +628,14 @@ API_CALL_RETRIES=1
 LOG_FILE="$HOME/.${SELF}.log"
 
 AUTO_DELETE_DELAY=""  # if set, uploaded image(s) will be deleted after this delay
-COPY_URL_TO_CLIP=true
-ENABLE_NOTIFICATIONS=true
-NOTIFY_LEVEL=INFO  # 'INFO' if all levels should be notified; 'ERROR' if only errors should be notified
 
-############## END CONFIG ##############
-
-# config items above can be overridden in $CONF_FILE
+# if the config file exists and is not empty...
 if [[ -s "$CONF_FILE" ]]; then
+	# load configuations
 	source "$CONF_FILE"
 fi
+
+############## END CONFIG ##############
 
 
 while [[ "$1" == -* ]]; do
@@ -730,8 +666,7 @@ while [[ "$1" == -* ]]; do
 done
 
 
-setup
-[[ $# -eq 0 ]] && { err -LN "no input given"; usage; exit 1; }
+[[ $# -eq 0 ]] && { err -L "No input given"; usage; exit 1; }
 [[ "$LOGIN" == true ]] && load_access_token
 
 if [[ "$MODE" == DELETE ]]; then
