post-review
- shebang to #!/usr/bin/env bash
- enforce bash ver >=4;
- remove dependency on jq;
- improve readme on auto-delete function;
- sanitize auto-delete delay value to deconds;
- default success stdout message reverted to original;
- create $CONF_ROOT dir if doesn't exist;
- parse values from input url using sed instead of perl;

diff --git a/imgurbash2 b/imgurbash2
--- a/imgurbash2
+++ b/imgurbash2
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # Copyright (c) 2016-2017 Ramon <https://github.com/ram-on/imgurbash2>
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
@@ -23,8 +23,11 @@
 # AUTHORS:  Ramon <https://github.com/ram-on/imgurbash2>
 #           Originally written by Bart Nagel <bart@tremby.net>
 #           Config & auth logic inspired by https://github.com/jomo/imgur-screenshot/
-# REQUIRED: curl, jq
-# OPTIONAL: xsel or xclip for copying URLs to your clipboard (linux)
+# REQUIRED: curl
+# OPTIONAL:
+#    * xsel or xclip for copying URLs to your clipboard (Linux)
+#    * notify-send for notifications (Linux)
+#    * growlnotify or terminal-notifier for notifications (macOS)
 #--------------------------------------------------------------------
 #
 # The URLs will be output on your terminal. If you have xsel or xclip they
@@ -76,7 +79,9 @@ usage() {
         ${COLORS[GREEN]}-d, --delete${COLORS[OFF]} <delete_hash1> [delete_hash2...]
             Deletes image(s) based on supplied delete hash.
         ${COLORS[GREEN]}-D, --auto-delete${COLORS[OFF]} <delay>
-            Where <delay> is argument accepted by \$sleep (eg 20, 15m, 1h).
+            Where <delay> is how long we should wait before deletion; seconds
+            by default, but accepts [smhdwM] suffix; eg 20, 15m, 1h.
+            s - sec, m - min, h - hour, d - day, w - week, M - month (30d).
             If provided, uploaded image(s) will be automatically deleted
             after given time has elapsed; note this assumes your computer
             won't be halted/suspended before the time has passed.
@@ -112,16 +117,6 @@ is_valid_url() {
 	regex='https?://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
 
 	[[ "$url" =~ $regex ]]
-}
-
-
-# Checks whether given string is empty or 'null'.
-#
-# @param {string}  str   string to check.
-#
-# @returns {bool}  true, if provided string is empty or 'null'
-is_null_or_empty() {
-	[[ -z "$*" || "$*" == null ]]
 }
 
 
@@ -195,7 +190,7 @@ upload_image() {
 #
 # @returns {void}
 notify() {
-	local opt ttl lvl msg default_ttl
+	local opt ttl lvl msg default_ttl OPTIND
 
 	default_ttl=5000
 
@@ -218,16 +213,53 @@ notify() {
 	if [[ "$IS_MAC" -eq 1 ]]; then
 		if which growlnotify &>/dev/null; then
 			growlnotify --title "$SELF" --message "$msg"
-		else
+		elif which terminal-notifier &>/dev/null; then
 			terminal-notifier -title "$SELF" -message "$msg"
 		fi
-	else
+	elif command -v notify-send &>/dev/null; then
 		if [[ "$lvl" == ERROR ]]; then
-			notify-send -a ImgurScreenshot -u critical -c "im.error" -t "$ttl" "$SELF" "$msg"
+			notify-send -u critical -c "im.error" -t "$ttl" "$SELF" "$msg"
 		elif [[ "$NOTIFY_LEVEL" != ERROR ]]; then
-			notify-send -a ImgurScreenshot -u low -c "transfer.complete" -t "$ttl" "$SELF" "$msg"
+			notify-send -u low -c "transfer.complete" -t "$ttl" "$SELF" "$msg"
 		fi
 	fi
+}
+
+
+# Parses string field value from given json input.
+#
+# E.g.  '"error":"Invalid client_id"' ==> string = "error", value = "Invalid client_id"
+#
+# @param {string}  input  input JSON to parse value from.
+# @param {string}  field  non-nested (ie you can't do field.nestedfield) json
+#                         field whose value we're interested in.
+#
+# @returns {string}  value for given field, extracted from given input json.
+parse_str_field() {
+	local input field
+
+	input="$1"
+	field="$2"
+
+	sed -e 's/.*\"'"$field"'\":"\([^"]*\).*/\1/' <<< "$input"
+}
+
+
+# Parses non-string field value (number, bool) from given json input.
+#
+# E.g.  '"status":200' ==> string = "status", value = "200"
+#
+# @param {string}  input  input JSON to parse value from.
+# @param {string}  field  non-nested (ie you can't do field.nestedfield) json
+#                         field whose value we're interested in.
+#
+# @returns {string}  value for given field, extracted from given input json.
+parse_nonstr_field() {
+	local input field
+
+	input="$1"
+	field="$2"
+	sed -e 's/.*\"'"$field"'\":\([^,}]*\).*/\1/' <<< "$input"
 }
 
 
@@ -244,8 +276,8 @@ copy_to_clipboard() {
 	if [[ "$IS_MAC" -eq 1 ]]; then
 		pbcopy <<< "$input"
 	elif [[ -n "$DISPLAY" ]]; then
-		{ command -v xsel >/dev/null 2>/dev/null && echo -n "$input" | xsel --input --clipboard; } \
-			|| { command -v xclip >/dev/null 2>/dev/null && echo -n "$input" | xclip -selection clipboard; } \
+		{ command -v xsel &>/dev/null && echo -n "$input" | xsel --input --clipboard; } \
+			|| { command -v xclip &>/dev/null && echo -n "$input" | xclip -selection clipboard; } \
 			|| err -L "didn't copy to clipboard - xsel nor xclip are installed"
 	else
 		err -L "Haven't copied to the clipboard:  no \$DISPLAY"
@@ -268,16 +300,17 @@ upload_images() {
 		is_request_success "$response" || { err "uploading [$file] failed"; HAS_ERRORS=1; continue; }
 
 		# get image url link
-		url="$(jq -r .data.link <<< "$response")"
+		url="$(parse_str_field "$response" link | sed -e 's/\\//g')"
 		is_valid_url "$url" || err "uploaded image resulted in [$url] link"
-		dhash="$(jq -r .data.deletehash <<< "$response")"
-		is_null_or_empty "$dhash" && err "no deletehash found in image [$file] upload response [$response]"
+		dhash="$(parse_str_field "$response" deletehash)"
+		[[ -z "$dhash" ]] && err "no deletehash found in image [$file] upload response [$response]"
 
-		info "[$file] uploaded: $url deletehash=[$dhash] (https://imgur.com/delete/${dhash})"
+		info -S "[$file] uploaded: $url deletehash=[$dhash] (https://imgur.com/delete/${dhash})"
+		echo -e "$url (Delete Hash = $dhash)"  # keep old stdout message for backwards compatibility
 
 		if [[ -n "$AUTO_DELETE_DELAY" ]]; then
 			info "Deleting image [$url] in $AUTO_DELETE_DELAY"
-			nohup /bin/bash -c "sleep $AUTO_DELETE_DELAY && delete_image_auto '$dhash' '$url'" >/dev/null 2>&1 &
+			nohup /bin/bash -c "sleep $AUTO_DELETE_DELAY_SEC && delete_image_auto '$dhash' '$url'" &>/dev/null &
 		fi
 
 		[[ "$COPY_URL_TO_CLIP" == true ]] && copy_to_clipboard "$url"
@@ -311,15 +344,17 @@ delete_images() {
 #
 # @returns {bool}  true, if request was successful.
 is_request_success() {
-	local response status success
+	local response status success error
 
 	response="$1"
 
-	status="$(jq -r .status <<< "$response")"
-	success="$(jq -r .success <<< "$response")"
+	success="$(parse_nonstr_field "$response" success)"
 
 	if [[ "$success" != true ]]; then
-		err -N "request failed with status [$status]: $(jq -r .data.error <<< "$response")"
+		status="$(parse_nonstr_field "$response" status)"
+		error="$(parse_str_field "$response" error)"
+
+		err -N "request failed with status [$status]: $error"
 		return 1
 	fi
 
@@ -371,16 +406,18 @@ fail() {
 #
 # @param {opt}      -N   OPTIONAL; don't open notification window.
 # @param {opt}      -L   OPTIONAL; don't log the message.
+# @param {opt}      -S   OPTIONAL; don't print message to stderr.
 # @param {string}   msg   message.
 #
 # @returns {void}
 info() {
-	local opt no_notif no_log msg OPTIND
+	local opt no_notif no_log no_stdout msg OPTIND
 
-	while getopts "NL" opt; do
+	while getopts "NLS" opt; do
 		case "$opt" in
 			N) no_notif=1 ;;
 			L) no_log=1 ;;
+			S) no_stdout=1 ;;
 			*) usage; fail ;;
 		esac
 	done
@@ -388,7 +425,9 @@ info() {
 
 	msg="$1"
 
-	>&2 echo -e "${COLORS[YELLOW]}${SELF}:${COLORS[OFF]} ${msg:-"--info lvl message placeholder--"}"
+	if [[ "$no_stdout" -ne 1 ]]; then
+		>&2 echo -e "${COLORS[YELLOW]}${SELF}:${COLORS[OFF]} ${msg:-"--info lvl message placeholder--"}"
+	fi
 
 	if [[ "$no_notif" -ne 1 ]]; then
 		notify INFO "$msg"
@@ -396,6 +435,46 @@ info() {
 
 	if [[ "$no_log" -ne 1 ]]; then
 		echo "INFO [$JOB_ID] $msg" >> "$LOG_FILE"
+	fi
+}
+
+
+# Performs initialisation (eg checks)
+#
+# @returns {void}
+setup() {
+
+	[[ -d "$CONF_ROOT" ]] || mkdir -p -- "$CONF_ROOT"
+	[[ "${BASH_VERSINFO[0]}" -lt 4 ]] && fail "bash ver 4 or above required, you have [${BASH_VERSINFO[0]}]"
+	check_dependencies || fail -L "please install required dependencies"
+	[[ -n "$AUTO_DELETE_DELAY" ]] && sanitize_auto_delete_delay
+}
+
+
+# Sanitizes AUTO_DELETE_DELAY param and expands it into seconds-only global
+# variable AUTO_DELETE_DELAY_SEC
+#
+# @returns {void}
+sanitize_auto_delete_delay() {
+	local to_sec_conversions suffix
+
+	[[ "$AUTO_DELETE_DELAY" =~ ^[0-9]+[smhdwM]?$ ]] || fail "incorrect delay param provided: [$AUTO_DELETE_DELAY]"
+
+	declare -Ar to_sec_conversions=(
+		[s]=1
+		[m]=60
+		[h]=3600
+		[d]=86400
+		[w]=604800
+		[M]=2592000
+	)
+	suffix="${AUTO_DELETE_DELAY:$(( ${#AUTO_DELETE_DELAY} - 1)):1}"
+
+	if ! [[ "$suffix" =~ ^[0-9]+$ ]]; then
+		AUTO_DELETE_DELAY_SEC="${AUTO_DELETE_DELAY:0:$(( ${#AUTO_DELETE_DELAY} - 1))}"
+		AUTO_DELETE_DELAY_SEC="$(( AUTO_DELETE_DELAY_SEC * to_sec_conversions[$suffix] ))"
+	else
+		AUTO_DELETE_DELAY_SEC="$AUTO_DELETE_DELAY"
 	fi
 }
 
@@ -408,8 +487,8 @@ check_dependencies() {
 	local prog fail
 
 	fail=0
-	for prog in curl jq; do
-		command -v "$prog" >/dev/null || { err -L "[$prog] not installed"; fail=1; }
+	for prog in curl; do
+		command -v "$prog" &>/dev/null || { err -L "[$prog] not installed"; fail=1; }
 	done
 
 	return $fail
@@ -450,6 +529,10 @@ load_access_token() {
 init_auth() {
 	local url expires_in
 
+	_parse() {
+		sed -e 's/.*'"$1"'=\(\w\+\).*/\1/' <<< "$url"
+	}
+
 	if [[ -z "$CLIENT_ID" ]]; then
 		read -r -p 'imgur client ID: ' CLIENT_ID
 		[[ -z "$CLIENT_ID" ]] && fail -NL "no clientId given, abort"
@@ -470,9 +553,9 @@ init_auth() {
 		read -r -p 'redirect url: ' url
 		[[ -z "$url" ]] && fail -NL "given redirect url [$url] doesn't look right"
 
-		ACCESS_TOKEN="$(perl -nle 'print $& if m{(access_token=)\K\w+}' <<< "$url")"
-		REFRESH_TOKEN="$(perl -nle 'print $& if m{(refresh_token=)\K\w+}' <<< "$url")"
-		expires_in="$(perl -nle 'print $& if m{(expires_in=)\K\w+}' <<< "$url")"
+		ACCESS_TOKEN="$(_parse access_token)"
+		REFRESH_TOKEN="$(_parse refresh_token)"
+		expires_in="$(_parse expires_in)"
 
 		persist_tokens "$expires_in"
 	fi
@@ -495,9 +578,9 @@ refresh_access_token() {
 		"$TOKEN_URL")"
 
 	[[ $? -ne 0 ]] && fail "refreshing access_token failed"
-	ACCESS_TOKEN="$(jq -r .access_token <<< "$response")"
-	REFRESH_TOKEN="$(jq -r .refresh_token <<< "$response")"
-	expires_in="$(jq -r .expires_in <<< "$response")"
+	ACCESS_TOKEN="$(parse_str_field "$response" access_token)"
+	REFRESH_TOKEN="$(parse_str_field "$response" refresh_token)"
+	expires_in="$(parse_nonstr_field "$response" expires_in)"
 
 	persist_tokens "$expires_in"
 }
@@ -517,11 +600,11 @@ persist_tokens() {
 
 	tmp="/tmp/.${SELF}-$RANDOM"
 
-	if is_null_or_empty "$ACCESS_TOKEN"; then
+	if [[ -z "$ACCESS_TOKEN" ]]; then
 		fail "[\$access_token] is missing"
-	elif is_null_or_empty "$REFRESH_TOKEN"; then
+	elif [[ -z "$REFRESH_TOKEN" ]]; then
 		fail "[\$refresh_token] is missing"
-	elif is_null_or_empty "$expires_in"; then
+	elif [[ -z "$expires_in" ]]; then
 		fail "[\$expires_in] is missing"
 	fi
 
@@ -583,7 +666,7 @@ API_CALL_RETRIES=1
 
 LOG_FILE="$HOME/.${SELF}.log"
 
-AUTO_DELETE_DELAY=""  # if set, uploaded image(s) will be deleted after this delay; value should be accepted by $sleep
+AUTO_DELETE_DELAY=""  # if set, uploaded image(s) will be deleted after this delay
 COPY_URL_TO_CLIP=true
 ENABLE_NOTIFICATIONS=true
 NOTIFY_LEVEL=INFO  # 'INFO' if all levels should be notified; 'ERROR' if only errors should be notified
@@ -624,7 +707,7 @@ while [[ "$1" == -* ]]; do
 done
 
 
-check_dependencies || fail -L "please install required dependencies"
+setup
 [[ $# -eq 0 ]] && { err -LN "no input given"; usage; exit 1; }
 [[ "$LOGIN" == true ]] && load_access_token
 
